### ISSUE TITLE
(Meta) Improve Source-Derived Documentation

### ISSUE THREAD

**Issue by myhndl** [polyswarm/development#29]
**Is your feature request related to a problem? Please describe.**
We need to auto-generate docs from source code and API descriptions.

**Describe the solution you'd like**

Read the Docs (or the like) on:
* [ ] polyswarm-client: https://github.com/polyswarm/development/issues/17
* [ ] polyswarmd
* [ ] relay
* [ ] contracts

Let's start with these and maybe later do:
* [ ] worker-registry

API auto-generation for:
* [ ] polyswarmd: https://github.com/polyswarm/polyswarmd/issues/51

Other:
* [ ] source * API-level docs are referenced by docs.polyswarm.io

**Additional context**
Related: https://github.com/polyswarm/ambassador/issues/17
